### ISSUE TITLE
IPV6 address http redirect https has an error

### ISSUE THREAD

**Issue by CarrieQi** [openbmc/phosphor-misc#1]
When use IPV6 address to visit web, http redirect https has an error, the error message is : 400 Bad request. 

in http-redirect.awk line 147, IPV6 address does not pass regular expression verification.
```
function find_host()
{
  ...
  # A very relaxed check for domainlabel or IPv4.
	if (host !~ /^[0-9a-zA-Z.-]+$/)
		respond_error(400)
}
```
I think the IP address format is correct when the code here has received the request.  So I commented out the code here first.

Then I met a new problem：The location in the response header is not set. I found it was because IPV6 address does not pass regular expression verification in function bad_uric.

Can you help me solve this problem？

@mdmillerii

**Comment by mdmillerii** [comment]
There is a review up but it needs some refinement.   I believe I'd like to see the ipv6 brackets and host to be recognized separately from the loosely parsed ipv4 and ipv6.   https://gerrit.openbmc.org/c/openbmc/phosphor-misc/+/47294

Also be aware there's a counter proposal to implement this natively in bmcweb https://gerrit.openbmc.org/c/openbmc/bmcweb/+/35265
